### PR TITLE
Added note about preferring HTML over PDFs

### LINKED ISSUE #130: Add Note About Preferring HTML over PDFs
From the accessibility guide:
https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#11-use-w3c-technologies-and-guidelines

> Use accessible technology specified by W3C such as HTML and CSS while avoiding PDF and Shockwave which is not as readily accessible. When utilizing PDF documents provide an alternative HTML page wherever possible. Alternatively, PDF documents may be used PROVIDED they meet the accessible PDF guidelines listed below.

### PR DESCRIPTION
**Pull request by loganfranken**
Fixes #130

### CODE REVIEW

**Comment by loganfranken** [comment]
Hey there! Anything I can do to help get this merged?

**Comment by garster** [comment]
@loganfranken the branch cannot be merged due to a conflict. 

Also I would like to see some expanded info an why not to use PDF. Personally I would expend it to explain how a PDF or any non-native format like a word processor document required external readers and break the flow of navigating the site.

**Comment by loganfranken** [comment]
Updated! Thanks @garster!

**Comment by garster** [comment]
@loganfranken, Wonderful. And thank you for not saying PDF Format (Portable Document Format Format)

**Pull request merged**
