### PR TITLE
Add Tip About Pop-up Windows

### LINKED ISSUE #129: Add Note About Pop-up Windows
From the accessibility guide:
https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#10-use-interim-solutions

> Do not use pop-up windows. They inhibit the ability of screen readers to read the desired active screen.

### PR DESCRIPTION
**Pull request by loganfranken**
Fixes #129

### CODE REVIEW

**Comment by loganfranken** [comment]
Hey there! Anything needed to merge this?

**Comment by loganfranken** [comment]
Good morning! Does this look good to merge?

**Comment by garster** [comment]
@loganfranken I'll merge once the conflict is resolved.

**Comment by loganfranken** [comment]
Fixed! Thanks @garster!

**Comment by garster** [comment]
@loganfranken more conflicts, from merging in the other PR

**Comment by loganfranken** [comment]
Thanks @garster!

**Pull request merged**
