### PR TITLE
Added Section on SSL TLS Everywhere

### LINKED ISSUE #271: Consider Incorporating Wiki Page: "SSL TLS Everywhere"
https://github.com/ucsb-wsg/ucsb-wsg.github.io/wiki/SSL-TLS-Everywhere

### PR DESCRIPTION
**Pull request by loganfranken**
Fixes #271

### CODE REVIEW

**Comment by loganfranken** [comment]
Hey there! Does this look good to merge in? Anything I need to change?

**Comment by garster** [comment]
OMG yes!

But, I would suggest removing references to SSL since it is obsolete.

Title:
"HTTPS Everywhere"
- Matches the name of the EFF plugin https://en.wikipedia.org/wiki/HTTPS_Everywhere
- https:// is what people *see* in the address bar

Remove:
or Secure Socket Layer (SSL)

**Comment by loganfranken** [comment]
Updated! Thanks @garster!

**Comment by garster** [comment]
My last pull request approval as co-chair!

**Pull request merged**
