### PR TITLE
Web Guide Redesign

### LINKED ISSUE #3: Responsive Design
The Web Standards Guide should have a responsive design to fit in line with our recommendations (http://www.ucsb.edu/webguide/viewport-dimensions).

### PR DESCRIPTION
**Pull request by loganfranken**
Integrates @ericmayes work on the Web Guide redesign! Woo!

Fixes #3 and #92

Design can be previewed here:
http://loganfranken.github.io/ucsb-wsg.github.io/

There are probably a few issues we will want to fix here and there.

My vote is to just merge the pull request and fix the issues as we go along since I think it fits best with the guide's/group's newer ethos as something that continues to evolve out in the open.

I'm totally down to taking the alternate approach of smoothing out all of the rough edges before we go live, though.

### CODE REVIEW

**Comment by tenken** [comment]
@loganfranken and @ericmayes

#### This looks like great work! And an awesome design! I vote we merge it.

Is it possible to get a mile-high 500 words or less (1 page) writeup on the Wiki about the theme's implementation (maybe we could link it to a tag of this merge). By writeup I mean someone could copy/paste my bullet points and just answer them directly to cut down on rewriting this:
-  Eg, What/Why version X.Y of Bootstrap is in use. Any gotchas for future updating regarding alter bootsrap in any odd ways?
- Why is there a lack of SASS variables used for colors or anything?
- what current breakpoints are in use.
- why were some vendor prefixes used `-moz-border-radius`, etc. Was a tool like Prefixer used or is this hardcoded due to a statusquo seen on like caniuse.com which should be tracked by future designers.
- Is there a known convention or recommendation on the number of significant figures used: `width: 8.33333%` as opposed to say `8.3%` etc.
-  If we removed hardcoded javascript dependencies, what are the version(s) of JS libraries currently in use on the site, or if Gulp states the version simply note it. Oddly, the Google Font is included remotely (it could also be made apart of the site by downloading the asset and inlining the font-src directive).
- What is the point of `ie10-viewport-bug-workaround` if this is a known issue is there an issue queue link available on the web someplace for this with regards to the browser version or bootstrap; can this be watched for eventual removal of this workaround.

My points above are not to detract from the work in any way but to help outline some points that could be added in documentation to help the transparency of the project in on-going maintenance. As in the past we've noted a lack of new-contribuor helper documentation. The current designer/merger would likely have the most direct feedback possible; but if unable I can likely go spelunking across the web to find answers to the above and create such a document.

**Comment by loganfranken** [comment]
Thanks @tenken!

Answers to your questions (I'll rough draft them here first, and then maybe we can bring them into the wiki after):

**Eg, What/Why version X.Y of Bootstrap is in use. Any gotchas for future updating regarding alter bootsrap in any odd ways?**

v3.3.5

I don't personally know of any gotchas with upgrading Bootstrap.

**Why is there a lack of SASS variables used for colors or anything?**

@ericmayes didn't originally use any Sass: he just wrote it all in raw CSS. I figured we could just roll back through and make use of Sass functionality after the fact.

**what current breakpoints are in use.**

From `main.scss`:

``` css
@media (min-width: 480px) {}
@media (min-width: 768px) {}
@media (min-width: 992px) {}
@media (min-width: 1200px) {}
@media (min-width: 480px) and (max-width: 768px) {}
@media (max-width: 969px) {}
```

And then whatever Bootstrap uses:
http://getbootstrap.com/css/#grid-media-queries

**why were some vendor prefixes used -moz-border-radius, etc. Was a tool like Prefixer used or is this hardcoded due to a statusquo seen on like caniuse.com which should be tracked by future designers.**

@ericmayes might have the answers for this; I'm imaging it was professional judgement at the time. I think it makes since for us to touch this up with [autoprefixer](https://github.com/postcss/autoprefixer) at some point.

**Is there a known convention or recommendation on the number of significant figures used: width: 8.33333% as opposed to say 8.3% etc.**

Not that I know of, no. @ericmayes might have more information, but I imagine the extra 3s might have been to address fussy rounding issues.

**If we removed hardcoded javascript dependencies, what are the version(s) of JS libraries currently in use on the site, or if Gulp states the version simply note it.**
- bootstrap.min.js: 3.3.5
- ie10-viewport-bug-workaround.js: Latest
- jquery.js: 1.11.3

**Oddly, the Google Font is included remotely (it could also be made apart of the site by downloading the asset and inlining the font-src directive).**

Yeah, we could totally bring in the Google Font as a local resource; little more work to get it to work cross-browser (which is the key benefit of serving from Google IMO), but definitely not a huge hurdle.

**What is the point of ie10-viewport-bug-workaround if this is a known issue is there an issue queue link available on the web someplace for this with regards to the browser version or bootstrap; can this be watched for eventual removal of this workaround.**

Looks like it's part of Bootstrap:
https://github.com/twbs/bootstrap/blob/master/docs/assets/js/ie10-viewport-bug-workaround.js

I don't think this is something that will get fixed; we may want to assess whether or not it's necessary given our audience/whether the bug in question actually afflicts the website.

---

Ultimately, what I'd love to see: each time someone finds an issue with the new redesign, we (1) fix it, but (2) also ensure the underlying reason we fixed it is documented within the web guide.

This way improving the web guide design also reflexively improves the web guide's content.

**Comment by ericmayes** [comment]
So nice to see this integrated! Thanks Logan! I just noticed one thing I guess I missed. The padding-top attribute inside the following media query might be better as 0. Right now the menu bar doesn't look balanced when its closed: 

@media (min-width: 768px)
#ucsb-nav .nav-primary ul li.dropdown a.dropdown-title {
    padding: 0px 5px 10px 20px;
}

I also notice the UCSB Wordmark logo is missing in the top left corner. This was because I had it referenced in a parent level images folder when I packaged the template folder and I forgot to include that image and change the reference. I think I sent the image in a separate email once I realized my mistake.

We also might want to add a little more padding to the main content area, with the actual content added instead of my test content it almost looks like the content expands past the menu and footer boxes (even though it doesn't) 

Good idea for the write-up David! Thanks for responding Logan, I will attempt to add to some of these now:

**Why is there a lack of SASS variables used for colors or anything?**

I figured the raw CSS might be easier to update on the server if we needed to make quick changes without having to recompile any SASS files. If this wont cause any problems, then I agree we should at the very least update color variables, vendor prefix mixins, etc. 

**why were some vendor prefixes used -moz-border-radius, etc. Was a tool like Prefixer used or is this hardcoded due to a statusquo seen on like caniuse.com which should be tracked by future designers.**

I stuck to the prefixes that Public Affairs used in their CSS. Border radius shouldnt need prefixes. The only ones I usually use are for gradients and box sizing. Using a n auto-prefixer for this would be preferable to me.

**Is there a known convention or recommendation on the number of significant figures used: width: 8.33333% as opposed to say 8.3% etc.**

This is again in correlation with what Public Affairs decided to use.

**Comment by garster** [comment]
Why such an old version of jQuery? 1.11.3 released in April/2015, and the 1.x line. Anything specific needed?

**Comment by loganfranken** [comment]
Thanks @garster! I created an issue for each individual suggestion.

**Pull request merged**
