### PR TITLE
Fix nav-collapses to allow ONLY the "WEBGUIDE CONTENTS" bar to trigger the expand/collapse event

### LINKED ISSUE #340: Nav collapses when clicking in whitespace next to page content
I feel this is a bug. If you click in any of the white area outside of the page content, the top nav collapses. When clicking again it does not expand. Even way down at the bottom.

The clickable event area should be the same for expand and collapse.

The current clickable area is unrelated to the menu. People may click there to change focus or move the window causing an unexpected event.

Only the "WEBGUIDE CONTENTS" bar should trigger the expand/collapse event.

image

### PR DESCRIPTION
**Pull request by a3roman**
Fixes #340

### CODE REVIEW

**Comment by a3roman** [comment]
Have you had a chance to review this issue? Please let me know if there is there anything else I need to do for it. Thank you!

**Comment by loganfranken** [comment]
Just throwing in my two cents: this PR looks good to me!

**Comment by loganfranken** [comment]
Hey there! I've noticed this PR has been out here for a little bit. It looks good to me, anything needed to merge it in?

**Comment by dsaludares** [comment]
@BwolfUCSB or @sbbeachvball Can one of you merge this PR?  I no longer have access.  Thanks!

**Comment by ghost** [comment]
Sure

Can I call you later to go over how to do it? I have not used GitHub.

Brian Wolf
Web Designer / Developer
Life Sciences Computing Group
UC Santa Barbara

Phone: 805.893.5932
Email: brian.wolf@lscg.ucsb.edu
Portfolio: webdesign.lscg.ucsb.edu

**Comment by dsaludares** [comment]
@BwolfUCSB Yes, no problem!

**Comment by loganfranken** [comment]
Hey there @BwolfUCSB and @sbbeachvball! Any updates on merging this one in?

**Comment by ghost** [comment]
HI Logan I will take a look today.

B

Brian Wolf
Web Designer / Developer
Life Sciences Computing Group
UC Santa Barbara

Phone: 805.893.5932
Email: brian.wolf@lscg.ucsb.edu
Portfolio: webdesign.lscg.ucsb.edu

**Comment by ghost** [comment]
approved.

**Comment by loganfranken** [comment]
Thanks @BwolfUCSB! And thanks for your work on this, @adrianaroman!

**Pull request merged**
