### PR TITLE
Serve Minified JavaScript and CSS

### LINKED ISSUE #6: Serve Minified JS/CSS
We should serve minified JS/CSS to fit with our recommendations (http://www.ucsb.edu/webguide/resources.php).

### PR DESCRIPTION
**Pull request by loganfranken**
(Fixes #6)

Minified CSS is now served using a "compressed" flag for the GitHub Pages sass plug-in.

Minified JS, unfortunately, was minified locally using UglifyJS2 and then committed. I wasn't able to find a better solution.

### CODE REVIEW

**Comment by fablio-work** [comment]
Hi Logan,
  Is it worthwhile committing the sass folder/files as well?  Or is that a bad workflow option?
I ask this in part because I am starting to use sass in various projects and am wrestling with 
this same “workflow” issue.

Aaron Martin  (CNT)
Earth Research Institute
6809 Ellison Hall
UCSB MS-3060
805-893-8415
aaron@eri.ucsb.edu mailto:aaron@eri.ucsb.edu

**Comment by tenken** [comment]
This project isn't using SASS.

But if you do use sass in a project then include the .sass or .scss files in a /scss folder and commit and file/folder combination such as /css-compiled/.gitkeep to track the css destination compilation directory within Git.

I recently started using Grav over the weekend and this is the approach I adopted from its Core installation.  http://getgrav.org/

**Comment by loganfranken** [comment]
This project _technically_ uses Sass: https://github.com/ucsb-wsg/ucsb-wsg.github.io/tree/master/style (note the `*.scss` extension)

We don't currently use any of the features, but since Sass is a superset of CSS, we still run it through the Sass preprocessor (which, in this pull request, handles the CSS minification for us too).

@fablio-work: Yeah, I think it's totally worthwhile: I actually would argue it's bad practice to commit the resulting CSS files since they are _technically_ a compiled asset.

**Comment by tenken** [comment]
I should read file extensions more often :), my bad.

Above I describe a means to track the compilation css directory in Git. You would also add that directory to your .gitignore directory for *.css files for example. But since git does not track empty directories -- hence the _convention_ (git doesnt care) of using .gitkeep within that folder in your project setup.

**Pull request merged**
